completed task
kaarenina/LAB-2021 pull request #1
Opened 2021-04-12 21:22 UTC by kaarenina

2021-04-14 11:22 UTC, serhii-shkodenko requested changes
Поправь, пожалуйста, эти замечания. Потом посмотрю еще раз.

2021-04-14 11:22 UTC, serhii-shkodenko commented on HomeWork.cs
> +            */
Комментарии следует делать на английсокм языке, если он действительно могут помочь.

2021-04-14 11:22 UTC, serhii-shkodenko commented on HomeWork.cs
> +            List<string> specialStreets = new List<string>() {"Wayne Street", "North Heather Street"};
Используй `var` для неявной типизации переменных. Здесь об этом [детальнее](https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/names-of-type-members#names-of-methods).

2021-04-14 11:22 UTC, serhii-shkodenko commented on HomeWork.cs
> +            List<decimal> specialStreetsValues = new List<decimal>() {10m, -5.36m};
Используй `var` для неявной типизации переменных. Здесь об этом [детальнее](https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/names-of-type-members#names-of-methods).

2021-04-14 11:22 UTC, serhii-shkodenko commented on HomeWork.cs
> +                List<int> newPriceST = destinations.Select((b,j) => b.Contains(specialStreets[i]) ? j : -1).Where(j => j != -1).ToList();
Используй `var` для неявной типизации переменных. Здесь об этом [детальнее](https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/names-of-type-members#names-of-methods).

2021-04-14 11:22 UTC, serhii-shkodenko commented on HomeWork.cs
> +                foreach(int index in newPriceST) pricesList[index] += specialStreetsValues[i];
Общепринятым является написание выражений циклов на следующей строке.

2021-04-14 11:22 UTC, serhii-shkodenko commented on HomeWork.cs
> +            decimal[] discount = new decimal[pricesList.Count];
Используй `var` для неявной типизации переменных. Здесь об этом [детальнее](https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/names-of-type-members#names-of-methods).

2021-04-14 11:22 UTC, serhii-shkodenko commented on HomeWork.cs
> +            foreach(int val in infantsIds) discount[val] += 50;
Общепринятым является написание выражений циклов на следующей строке.

2021-04-14 11:22 UTC, serhii-shkodenko commented on HomeWork.cs
> +            foreach(int val in childrenIds) discount[val] += 25;
Общепринятым является написание выражений циклов на следующей строке.

2021-04-14 11:22 UTC, serhii-shkodenko commented on HomeWork.cs
> +            for(int i = 1; i < pricesList.Count; i++ )
В этом цикле ты переберешь только чытере улицы из пяти, а надо все. Подумай еще, как можно избежать выхода за пределы массива.

2021-04-14 11:22 UTC, serhii-shkodenko commented on HomeWork.cs
> +            var pricesList = prices.ToList();
Для того чтобы пройтись Select по коллекции, тебе эти списки не нужны. Используй параметры.

2021-04-14 11:22 UTC, serhii-shkodenko commented on HomeWork.cs
> +                fullPrice = DiscountsCalc(destinations,  infantsIds, childrenIds, prices, currencies);
Не сокращай слова в именах идентификаторов.

2021-04-14 11:22 UTC, serhii-shkodenko commented on HomeWork.cs
> +            List<decimal> pricesList = prices.ToList();
Используй `var` для неявной типизации переменных. Здесь об этом [детальнее](https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/names-of-type-members#names-of-methods).

2021-04-14 11:22 UTC, serhii-shkodenko commented on HomeWork.cs
> +            List<string> destinationsList = destinations.ToList();
Используй `var` для неявной типизации переменных. Здесь об этом [детальнее](https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/names-of-type-members#names-of-methods).

2021-04-14 11:22 UTC, serhii-shkodenko commented on HomeWork.cs
> +            #region delivery calculation based on the street
Использование регионов сегодня считается bad practice.

2021-04-14 13:38 UTC, kaarenina commented
1 - Убрал явную типизацию во всех местах
2 - Выражения циклов на следующей строке
3 - Убрал regions
4 - Сокращения идентификатора исправлено
5 - Публичный метод перед приватными
6 - Убрал ненужные списки  в методе ConvertToUSD
7 - Что касается реализации применения скидок для подряд идущих улиц:

2021-04-14 13:38 UTC, kaarenina commented
1 - Убрал явную типизацию во всех местах
2 - Выражения циклов на следующей строке
3 - Убрал regions
4 - Сокращения идентификатора исправлено
5 - Публичный метод перед приватными
6 - Убрал ненужные списки  в методе ConvertToUSD
7 - Что касается реализации применения скидок для подряд идущих улиц:

2021-04-14 13:51 UTC, kaarenina commented
1 - Убрал явную типизацию во всех местах
2 - Выражения циклов на следующей строке
3 - Убрал regions
4 - Сокращения идентификатора исправлено
5 - Публичный метод перед приватными
6 - Убрал ненужные списки  в методе ConvertToUSD
7 - Что касается реализации применения скидок для подряд идущих улиц:
     Я наверное неправильно понял задание. Поскольку скидка 15% применяется только для последующих улиц. то в первая в списке улица никогда не получит скидку, то есть ее не нужно сравнивать ни с какой другой улицей. Или к ней тоже может применяться скидка, и ее надо сравнивать с последней в списке улицей?
     Я сравнивал вот так:
      Fairfield Court, Madison Heights, MI 48071 ==  Wayne Street, Hendersonville, NC 28792
      Wayne Street, Hendersonville, NC 28792 == North Heather Street, Cocoa, FL 32927
      North Heather Street, Cocoa, FL 32927 ==  North Heather Street, Cocoa, FL 32927
      North Heather Street, Cocoa, FL 32927 ==  Tarkiln Hill Ave, Middleburg, FL 32068
где первый столбик **i-1**, а второй - **i**,  и получается. что сравниваются все улицы, только в 4 итерациях.

2021-04-14 13:53 UTC, kaarenina commented on HomeWork.cs
> +            List<string> destinationsList = destinations.ToList();
Ок

2021-04-14 13:53 UTC, kaarenina commented on HomeWork.cs
> +            #region delivery calculation based on the street
Убрал

2021-04-14 13:53 UTC, kaarenina commented on HomeWork.cs
> +            List<decimal> pricesList = prices.ToList();
Ок

2021-04-14 13:53 UTC, kaarenina commented on HomeWork.cs
> +                fullPrice = DiscountsCalc(destinations,  infantsIds, childrenIds, prices, currencies);
Исправил

2021-04-14 13:54 UTC, kaarenina commented on HomeWork.cs
> +            var pricesList = prices.ToList();
Убрал ненужный список. Сократил количество кода

2021-04-14 13:54 UTC, kaarenina commented on HomeWork.cs
> +                foreach(int index in newPriceST) pricesList[index] += specialStreetsValues[i];
Исправил

2021-04-14 13:54 UTC, kaarenina commented on HomeWork.cs
> +            decimal[] discount = new decimal[pricesList.Count];
Ок

2021-04-14 13:55 UTC, kaarenina commented on HomeWork.cs
> +            */
Теперь на английском

2021-04-14 13:55 UTC, kaarenina commented on HomeWork.cs
> +            List<string> specialStreets = new List<string>() {"Wayne Street", "North Heather Street"};
Ок

2021-04-14 13:55 UTC, kaarenina commented on HomeWork.cs
> +            List<decimal> specialStreetsValues = new List<decimal>() {10m, -5.36m};
Ок

2021-04-14 13:55 UTC, kaarenina commented on HomeWork.cs
> +                List<int> newPriceST = destinations.Select((b,j) => b.Contains(specialStreets[i]) ? j : -1).Where(j => j != -1).ToList();
Ок

2021-04-14 13:56 UTC, kaarenina commented on HomeWork.cs
> +            for(int i = 1; i < pricesList.Count; i++ )
Я наверное неправильно понял задание. Поскольку скидка 15% применяется только для последующих улиц. то в первая в списке улица никогда не получит скидку, то есть ее не нужно сравнивать ни с какой другой улицей. Или к ней тоже может применяться скидка, и ее надо сравнивать с последней в списке улицей?
Я сравнивал вот так:
Fairfield Court, Madison Heights, MI 48071 == Wayne Street, Hendersonville, NC 28792
Wayne Street, Hendersonville, NC 28792 == North Heather Street, Cocoa, FL 32927
North Heather Street, Cocoa, FL 32927 == North Heather Street, Cocoa, FL 32927
North Heather Street, Cocoa, FL 32927 == Tarkiln Hill Ave, Middleburg, FL 32068
где первый столбик i-1, а второй - i, и получается. что сравниваются все улицы, только в 4 итерациях.

2021-04-15 19:34 UTC, serhii-shkodenko approved these changes
Логику проверил. Выглядит хорошо. На будущее лучше использовать для имен переменных слово `item` вместо `element`. Можно мержить.

2021-04-16 06:36 UTC, merged