Features/b2b b2c
kaarenina/LAB-2021 pull request #3
Opened 2021-04-28 08:23 UTC by kaarenina

2021-04-29 20:46 UTC, serhii-shkodenko requested changes

2021-04-29 20:46 UTC, serhii-shkodenko commented on b2c.implementation/Data/OrderDrive.cs
> +    public static class OrderDrive
Не стоит хранить данные в статических файлах. Я говорил об этом на встречах. Просмотри весь ПР и поправь везде, пожалуйста.

2021-04-29 20:46 UTC, serhii-shkodenko commented on b2c.implementation/Data/ProductDrive.cs
> +namespace b2c_implementation.Data
Это имя для неймспейса противоречит [известной конвенции](https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/names-of-namespaces). Подумай, пожалуйста, как можно по-другому его назвать.

2021-04-29 20:46 UTC, serhii-shkodenko commented on b2c.implementation/Services/OrderService.cs
> +        private static List<Product> products = new List<Product>();
Для хранения данных лучше предусмотреть отдельный класс.

2021-04-29 20:46 UTC, serhii-shkodenko commented on b2c.implementation/Services/OrderService.cs
> +    public static class OrderService
Для соблюдения Dependency inversion principle используй, пожалуйста, интерфейсы.

2021-04-29 20:46 UTC, serhii-shkodenko commented on b2c.implementation/UI/StoreUI.cs
> +    public class StoreUI : IUser
Название для этого интерфейса выглядит немного некосистентно с точки зрения его реализацией классом `StoreUI`. Назови его как то по-другому, пожалуйста.

2021-04-29 20:46 UTC, serhii-shkodenko commented on b2c.implementation/UI/UserInteraction.cs
> +    public class UserInteraction : IUser
Название для этого интерфейса выглядит немного некосистентно с точки зрения его реализацией классом `StoreUI`. Назови его как то по-другому, пожалуйста.

2021-05-02 16:46 UTC, kaarenina commented on b2c.implementation/Services/OrderService.cs
> +        private static List<Product> products = new List<Product>();
О нет, здесь не хранятся данные - это просто список индексов продуктов, которые выбрал пользователь, чтобы потом преобразовать в список объектов Product

2021-05-03 22:04 UTC, serhii-shkodenko requested changes

2021-05-03 22:04 UTC, serhii-shkodenko commented on b2c.implementation/Services/CustomerService.cs
> +    public static class CustomerService
Пожалуйста, перепиши этот класс в соответствии со следующими рекомендациями:

1. Класс, содержащий бизнес логику следует сделать нестатическим, реализующим интерфейс `ICustomerService`. Ему в качестве зависимости слудет передать, класс обеспечивающий доступ в хранилище, либо само хранилище. 
2. В методах `CustomerService` следует реализовать добавление/изменение/удаление данных в соответствии с бизнес правилами. В этих методах должны использоваться переданные зависимости. 

Все остальные классы, реализующие функции по добавлению/изменению/удалению сущностей в хранилище, перепиши, пожалуйста, с учетом вышеописанных рекомендаций.

2021-05-03 22:04 UTC, serhii-shkodenko commented on b2c.implementation/Services/CustomerService.cs
> +        public static string customerName { get; set; }
Не стоит хранить состояние класса в статической переменной. Удали ее. В соответствии с вышеуказанными рекомендациями тебе не понадобится хранить состояние в этом классе. Кроме того имена свойств должны быть в `PascalCase`. Это касается и всех остальрых статических классов в этом ПР. Поправь везде, пожалуйста.

2021-05-03 22:04 UTC, serhii-shkodenko commented on b2c.implementation/Services/StoreService.cs
> +    static class StoreService
Перепиши все статические файлы в твоем ПР, руководствуясь вышеуказанными рекомендациями.

2021-05-06 12:53 UTC, serhii-shkodenko requested changes

2021-05-06 12:53 UTC, serhii-shkodenko commented on b2c.implementation/.vscode/launch.json
> +{
Этот файла не должно быть в репозитории. Добавить его в гитигнор и удали из ПР.

2021-05-06 12:53 UTC, serhii-shkodenko commented on b2c.implementation/.vscode/tasks.json
> +{
Этот файла не должно быть в репозитории. Добавить его в гитигнор и удали из ПР.

2021-05-11 21:40 UTC, serhii-shkodenko requested changes

2021-05-11 21:40 UTC, serhii-shkodenko commented on b2c.implementation/Services/CustomerService.cs
> +        public void CreateOrder(string[] selectedProduct)
Параметр лучше назвать во множественном числе, ведь тип переменной - массив.

2021-05-11 21:40 UTC, serhii-shkodenko commented on b2c.implementation/UI/CustomerUI.cs
> +        public CustomerUI(OrderDrive orders, StoreDrive stores, ProductDrive products)
Здесь в качестве параметров оптимальнее в конструкторе определить твои сервисы с бизнес логикой, а не хранилище.

2021-05-11 21:40 UTC, serhii-shkodenko commented on b2c.implementation/UI/CustomerUI.cs
> +                    var newCustomer = new CustomerService(productCatalog);
`CustomerService` оптимально сделать зависимостью через инъекцию в конструктор.

2021-05-11 21:40 UTC, serhii-shkodenko commented on b2c.implementation/UI/StoreUI.cs
> +        public StoreUI(StoreDrive stores, ProductDrive products)
Слой для работы с интерфейсом логично делать зависимым от слоя для работы с бизнес объектами, чтобы слой UI не работал напрямую со слоем храналища.

2021-05-11 21:40 UTC, serhii-shkodenko commented on b2c.implementation/UI/StoreUI.cs
> +                    var newstore = new StoreService(storeCatalog, productCatalog);
`StoreService` оптимально сделать зависимостью через инъекцию в конструктор.

2021-05-12 09:59 UTC, kaarenina commented
Поменял. У меня в UI сохраняется хранилище (класс Drive). А CustomerService и StoreService уже изменяют состояние хранилища, добавляют магазины, товары и тд.

2021-05-13 20:19 UTC, serhii-shkodenko requested changes

2021-05-13 20:19 UTC, serhii-shkodenko commented on b2c.implementation/Services/CustomerService.cs
> +        public IList<Product> selectedProducts {get; set;}
Этот свойство служит для сохранения состояния заказа, чтобы разные методы могли иметь к нему доступ. В то же время этот класс отвечает за бизнес логику, состояние, если вообще сохранять, то делать лучше это в слое для работы с интерфейсом. Как вариант, можно в хранилище сделать таблицу, куда сохранять несовершенные по каким-либо причинам заказы, и потом предоставлять бизнесу аналитику, почему тот или иной заказ не был до конца оформлен. 

Поскольку оно и публичное, и доступное для изменения, это нарушает сокрытие. 

По совокупности причин, это свойство лучше всего удалить.

2021-05-13 20:19 UTC, serhii-shkodenko commented on b2c.implementation/Services/CustomerService.cs
> +        public void CreateOrder(string[] selectedItems, IDrive catalog)
Здесь из параметров лучше убрать объект `IDrive` и сделать зависимостью твоего класса, поскольку он используется в нескольких методах.

2021-05-13 20:19 UTC, serhii-shkodenko commented on b2c.implementation/Services/CustomerService.cs
> +        public void SaveOrder(IDrive orders, string customerName, out int id)
Здесь из параметров лучше убрать объект `IDrive` и сделать зависимостью твоего класса, поскольку он используется в нескольких методах.

2021-05-13 20:19 UTC, serhii-shkodenko commented on b2c.implementation/Services/CustomerService.cs
> +            id = orders.Orders.Count + 1;
Этот метод опеределения `Id` в дальнейшем приведет к появлению сущностей с одинавыми номерами идентификаторов. Рассмотри, следующий пример:

1. В хранилище есть эелементы:
```
Order {Id = 1};
Order {Id = 2};
```

2. Удаляем первый элемент:
```
Order {Id = 2};
```

3. Вычисляем новый идентификатор и добавляем новый элемент:
```
Order {Id = 2};
Order {Id = 2};
```

Перепиши, пожалуйста, логику вычисления доступного `Id`.

2021-05-13 20:19 UTC, serhii-shkodenko commented on b2c.implementation/Services/StoreService.cs
> +            id = data.Stores.Count + 1;
Этот метод опеределения `Id` в дальнейшем приведет к появлению сущностей с одинавыми номерами идентификаторов. Рассмотри, следующий пример:

1. В хранилище есть эелементы:
```
Store {Id = 1};
Store {Id = 2};
```

2. Удаляем первый элемент:
```
Store {Id = 2};
```

3. Вычисляем новый идентификатор и добавляем новый элемент:
```
Store {Id = 2};
Store {Id = 2};
```

Перепиши, пожалуйста, логику вычисления доступного `Id`.

2021-05-13 20:19 UTC, serhii-shkodenko commented on b2c.implementation/Services/StoreService.cs
> +        public void AddItem(string storeName, IList<string> products, IDrive data, out int id)
Лучше сделать инъекцию объекта `IDrive` через конструктор класса.

2021-05-13 20:19 UTC, serhii-shkodenko commented on b2c.implementation/abstracts/IDrive.cs
> +        public void DefaultProducts();
Согласно [конвенции](https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/names-of-type-members#names-of-methods), в имени метод должен быть глагол. Можно добавить в него слово `Add`, например.

2021-05-13 20:19 UTC, serhii-shkodenko commented on b2c.implementation/abstracts/IDrive.cs
> +        public void DefaultStores();
Согласно [конвенции](https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/names-of-type-members#names-of-methods), в имени метод должен быть глагол. Можно добавить в него слово `Add`, например.

2021-05-14 13:41 UTC, kaarenina commented
Исправил замечания. Теперь, у меня UI не работает напрямую с хранилищем, список выбранных продуктов не сохраняется в классе, который отвечает за бизнес логику.

2021-05-16 00:01 UTC, serhii-shkodenko requested changes

2021-05-16 09:06 UTC, kaarenina commented
Исправил. Наполнение продуктами и магазинами по умолчанию теперь один метод  и вызывается в начале.
Исправил код в местах, где было нарушение Dependency inversion principle

2021-05-18 22:47 UTC, serhii-shkodenko requested changes

2021-05-18 22:47 UTC, serhii-shkodenko commented on b2c.implementation/Services/CustomerService.cs
> +        private IDrive Catalog {get;}
Обычно свойства применяют, чтобы дать доступ либо наследникам, либо вообще публичный. Приватными делают поля. Поэтому переделай, пожалуйста, это свойство в приватное `readonly` поле.

2021-05-18 22:47 UTC, serhii-shkodenko commented on b2c.implementation/Services/StoreService.cs
> +        public IDrive Storage {get; set;}
Переделай, пожалуйста, это свойство в приватное `readonly` поле.

2021-05-18 22:47 UTC, serhii-shkodenko commented on b2c.implementation/StartPanel.cs
> +        IDrive catalog;
Добавь модификатор доступа и модификатор `readonly`.

2021-05-18 22:47 UTC, serhii-shkodenko commented on b2c.implementation/UI/CustomerUI.cs
> +            newCustomer = new CustomerService(data);
Нарушение dependency inversion principle. Лучше, чтобы эта зависимость была определена в параметрах конструктора и сохранена в приватное `readonly` поле.

2021-05-18 22:47 UTC, serhii-shkodenko commented on b2c.implementation/UI/CustomerUI.cs
> +        private IDrive data;
Слой для работы с интерфейсом пользователя не может знать о слое для работы с данными. Он может знать о слое для работы с бизнес логикой. Поэтому удали, пожалуйста, эту зависимость. Для получения нужных бизнес объектов ты можешь использовать методы из `ICustomerService`, если нет каких-то методов, добавь их.

2021-05-18 22:47 UTC, serhii-shkodenko commented on b2c.implementation/StartPanel.cs
> +            catalog = new Drive();
Нарушение dependency inversion principle. Лучше, чтобы эта зависимость была определена в параметрах конструктора и сохранена в приватное `readonly` поле.

2021-05-18 22:47 UTC, serhii-shkodenko commented on b2c.implementation/UI/StoreUI.cs
> +            newStore = new StoreService(data);
Нарушение dependency inversion principle. Лучше, чтобы эта зависимость была определена в параметрах конструктора и сохранена в приватное `readonly` поле.

2021-05-18 22:47 UTC, serhii-shkodenko commented on b2c.implementation/abstracts/IDrive.cs
> +        public void AddDefaultProductsAndStores();
Модификаторы `public` в интерфейсе является модификатором по умолчанию, поэтому его опускают.

2021-05-18 22:47 UTC, serhii-shkodenko commented on b2c.implementation/abstracts/ICustomerService.cs
> +       public IEnumerable<Product> CreateOrder(IEnumerable<int> selectedItems);
Модификаторы `public` в интерфейсе является модификатором по умолчанию, поэтому его опускают.

2021-05-18 22:47 UTC, serhii-shkodenko commented on b2c.implementation/abstracts/ICustomerService.cs
> +       public void SaveOrder(string customerName, IEnumerable<Product> selectedProducts, out int id);
Модификаторы `public` в интерфейсе является модификатором по умолчанию, поэтому его опускают.

2021-05-18 22:47 UTC, serhii-shkodenko commented on b2c.implementation/UI/StoreUI.cs
> +        private IDrive data;
Добавь модификатор `readonly`.

2021-05-18 22:47 UTC, serhii-shkodenko commented on b2c.implementation/UI/StoreUI.cs
> +        private IStoreService newStore;
Добавь модификатор `readonly`.

2021-05-18 22:47 UTC, serhii-shkodenko commented on b2c.implementation/UI/CustomerUI.cs
> +        private ICustomerService newCustomer;
Добавь модификатор `readonly`.

2021-05-19 12:07 UTC, kaarenina commented
Теперь слой UI не знает о хранилище, переделал свойства в приватные поля, исправил ошибки з dependency inversion principle.

2021-05-19 12:24 UTC, serhii-shkodenko requested changes

2021-05-19 12:24 UTC, serhii-shkodenko commented on b2c.implementation/Services/StoreService.cs
> +        public IDrive GetData() => storage;
Пожалуйста, удали этот метод. Он предоставлет хранилище для всех потребителей, а его потребителями явлются методы из классов UI слоя. Ты организовал протекание абстракций. 

Общее правило гласит, что верхние слои твоей архитектуры не должны знать о нижних. При этом, например, слой бизнес логики может знать о слое для работы с данными, а UI слой - о бизнес слое. При этом UI слой не должен знать о слое с данными, а у тебя получается, что знает. 

Вместо предоставления данных напрямую для UI слоя, их лучше обработать в соответствии с бизнес правилами. То есть, преобразовать данные в бизнес объекты. 

Поэтому, сделай в твоих сервисах методы, которые буду обращаться к хранилищу за данными, определенным образом их обрабатывать и предоставлять по запросу для UI слоя. А UI слой вместо получения всего хранилища будет пользоваться методами из бизнес слоя.

2021-05-19 19:40 UTC, kaarenina commented
Кажется исправил, теперь UI получает от сервиса не все хранилище, а только сущность, и уже работает с этой сущностью: заказом или магазином.

2021-05-28 22:39 UTC, serhii-shkodenko requested changes

2021-05-28 22:39 UTC, serhii-shkodenko commented on b2c.implementation/Data/Drive.cs
> +namespace DeliveryService.B2cImplementation.Data
Имя этого неймспейса не очень описательное. Мне кажется, будеть достаточно просто `DeliveryService.Data`. Примени это изменение по всему проекту, пожалуйста.

2021-05-28 22:39 UTC, serhii-shkodenko commented on b2c.implementation/Models/Order.cs
> +
Удали пустую строку.

2021-05-28 22:39 UTC, serhii-shkodenko commented on b2c.implementation/Models/Order.cs
> +
Удали пустую строку.

2021-05-28 22:39 UTC, serhii-shkodenko commented on b2c.implementation/Models/Product.cs
> +
Удали пустую строку.

2021-05-28 22:39 UTC, serhii-shkodenko commented on b2c.implementation/Models/Product.cs
> +        public Product(string nameProduct, Store owner, decimal price)
Делать конструктор для класса с инициализацией всех свойств и оставлять при этом публичными сеттеры не несет в себе большого смысла. Обычно конструкторы применяют, когда нужно обеспечить иммутальность для свойства. Поэтому предлагаю либо оставить конструктор и сделать сеттер приватными, либо удалить конструктор и оставить сеттеры публичными. Это относится ко всем моделям.

2021-05-28 22:39 UTC, serhii-shkodenko commented on b2c.implementation/Models/Store.cs
> +
Удали пустую строку.

2021-05-28 22:39 UTC, serhii-shkodenko commented on b2c.implementation/Program.cs
> +    class Program
Добавь, пожлауйста, модификатор доступа.

2021-05-28 22:39 UTC, serhii-shkodenko commented on b2c.implementation/Services/CustomerService.cs
> +
Удали, пожалуйста, пустую строку.

2021-05-28 22:39 UTC, serhii-shkodenko commented on b2c.implementation/Services/CustomerService.cs
> +            catch (System.InvalidOperationException)
Я не вижу необходимости здесь применять try..catch. Удали, пожалуйста.

2021-05-28 22:39 UTC, serhii-shkodenko commented on b2c.implementation/Services/CustomerService.cs
> +                id = 1;
А что будет, если в коллекции уже существуюет элемент с данным Id? Лучше удалить эту логику.

2021-05-28 22:39 UTC, serhii-shkodenko commented on b2c.implementation/Services/CustomerService.cs
> +            foreach (var itemST in catalog.Stores)
Будет понятнее, если переменную назвать `store`.

2021-05-28 22:39 UTC, serhii-shkodenko commented on b2c.implementation/Services/CustomerService.cs
> +                Console.WriteLine("Store: " + itemST.Value);
Здесь в будущем будет логирование, поэтому удали этот вывод в консоль.

2021-05-28 22:39 UTC, serhii-shkodenko commented on b2c.implementation/Services/CustomerService.cs
> +                foreach (var itemPR in catalog.Products)
Будет понятнее, если переменную назвать `product`.

2021-05-28 22:39 UTC, serhii-shkodenko commented on b2c.implementation/Services/CustomerService.cs
> +                    Console.WriteLine(itemPR.Key + " - " + itemPR.Value.Name);
Здесь в будущем будет логирование, поэтому удали этот вывод в консоль.

2021-05-28 22:39 UTC, serhii-shkodenko commented on b2c.implementation/Services/CustomerService.cs
> +        public void DisplayProducts()
Этот метод отвечает за вывод на экран данных и при этом находится в классе, реализующий бизнес логику. Это нарушение Single responsibility principle. Пожалуйста, вынеси его в класс, отвечающий за UI.

2021-05-28 22:39 UTC, serhii-shkodenko commented on b2c.implementation/Services/StoreService.cs
> +
Удали, пожалуйста, пустую строку.

2021-05-28 22:39 UTC, serhii-shkodenko commented on b2c.implementation/Services/StoreService.cs
> +            catch (System.InvalidOperationException)
То же замечание по поводу try..catch (см. выше). Удали, его пожалуйста.

2021-05-28 22:39 UTC, serhii-shkodenko commented on b2c.implementation/StartPanel.cs
> +        public StartPanel(IDrive storage)
В классы, которые реализуют работу с UI должны приходить зависимости с бизнес логикой, а у тебя приходит хранилище. Переделай, пожалуйста.

2021-05-28 22:39 UTC, serhii-shkodenko commented on b2c.implementation/UI/CustomerUI.cs
> +        private readonly ICustomerService newCustomer;
Имя этого объекта не соответствут его типу. Тип говорит, что это сущность, отвечающая за манипулирование объетами типа покупатель, а имя переменной говорит, что он имеет тип покупателя. Лучше так и назвать эту переменную `_сustomerService`.

2021-05-28 22:39 UTC, serhii-shkodenko commented on b2c.implementation/UI/CustomerUI.cs
> +            return Console.ReadLine().Split().ToList().Select(item => Convert.ToInt32(item));
А что будет, если конвертация пройдет неудачно? Нужно добавить какую-то проверку.

2021-05-28 22:39 UTC, serhii-shkodenko commented on b2c.implementation/UI/StoreUI.cs
> +        private readonly IStoreService newStore;
Имя этого объекта не соответствут его типу. Тип говорит, что это сущность, отвечающая за манипулирование объетами типа магазин, а имя переменной говорит, что он имеет тип магазина. Лучше так и назвать эту переменную `_storeService`.

2021-05-28 22:39 UTC, serhii-shkodenko commented on b2c.implementation/UI/StoreUI.cs
> +        public StoreUI(IStoreService store)
Имя параметра лучше поменять на `storeService`.

2021-05-28 22:39 UTC, serhii-shkodenko commented on b2c.implementation/UI/CustomerUI.cs
> +        public CustomerUI(ICustomerService customer)
Имя параметра лучше поменять на `customerService`.

2021-05-28 22:39 UTC, serhii-shkodenko commented on b2c.implementation/abstracts/ICustomerService.cs
> +       void DisplayProducts();
Этот метод не должен находиться в этом интерфейсе, см. выше.

2021-06-01 17:08 UTC, kaarenina commented on b2c.implementation/Models/Product.cs
> +        public Product(string nameProduct, Store owner, decimal price)
Сделал свойствами для чтения, так как если я сделаю их приватными у меня не будет возможности выводить информацию о них в консоль

2021-06-01 17:12 UTC, kaarenina commented on b2c.implementation/Services/CustomerService.cs
> +            catch (System.InvalidOperationException)
На самом деле, если словарь заказов пуст будет исключение типа System.InvalidOperationException. Поэтому я и присваиваю в блоке catch id=1. А если не пуст - я нахожу максимальный Id и прибавляю к нему единицу

2021-06-01 20:13 UTC, yevhenbilushko commented on b2c.implementation/Data/Drive.cs
> +            Products.Add(9, new Product("Swiss",         Stores[1] , 100));
i think i got your idea about clear formating
but it does not work i mean it is better to rewrite to using single space
it is easier to maintain

2021-06-01 20:13 UTC, yevhenbilushko commented on b2c.implementation/Models/Order.cs
> +        public Order() {}
seems like it can be removed

2021-06-01 20:13 UTC, yevhenbilushko commented on b2c.implementation/Models/Order.cs
> +        public string Owner {get;}
please format spaces

2021-06-01 20:13 UTC, yevhenbilushko commented on b2c.implementation/Models/Order.cs
> +        public IEnumerable <Product> Products;
is it field or property
if field - better rename it to "products" and make private
if property - add accessors (set and get)

2021-06-01 20:13 UTC, yevhenbilushko commented on b2c.implementation/Models/Order.cs
> +        public Order(IEnumerable<Product> product, decimal price, string owner)
products

2021-06-01 20:13 UTC, yevhenbilushko commented on b2c.implementation/Models/Product.cs
> +        public Product(string nameProduct, Store owner, decimal price)
maybe better "productName" ?

2021-06-01 20:13 UTC, yevhenbilushko commented on b2c.implementation/Services/CustomerService.cs
> +        public CustomerService(IDrive catalog)
add line before method

2021-06-01 20:13 UTC, yevhenbilushko commented on b2c.implementation/Services/CustomerService.cs
> +            this.catalog = catalog;
rename field to "_catalog" as for readonly and then you can remove "this."

2021-06-01 20:13 UTC, yevhenbilushko commented on b2c.implementation/Services/CustomerService.cs
> +        public decimal GetOrderPrice(IEnumerable<Product> selectedProducts) => selectedProducts.Select(item => item.Price).Sum();
seems like you can write
selectedProducts.Sum(item => item.Price);

2021-06-01 20:13 UTC, yevhenbilushko commented on b2c.implementation/Services/CustomerService.cs
> +            catch (System.InvalidOperationException)
remove it
add using

2021-06-01 20:13 UTC, yevhenbilushko commented on b2c.implementation/Services/CustomerService.cs
> +            catch (System.InvalidOperationException)
+ к Сергею
на крайняк лови общую ошибку Exception

2021-06-01 20:13 UTC, yevhenbilushko commented on b2c.implementation/Services/StoreService.cs
> +
remove empty line

2021-06-01 20:13 UTC, yevhenbilushko commented on b2c.implementation/StartPanel.cs
> +            string status = Console.ReadLine();
seems like can be var

2021-06-01 20:13 UTC, yevhenbilushko commented on b2c.implementation/UI/CustomerUI.cs
> +
remove line

2021-06-01 20:13 UTC, yevhenbilushko commented on b2c.implementation/UI/CustomerUI.cs
> +                Console.WriteLine("-----> " + item.Name);
please add brackets

2021-06-01 20:13 UTC, yevhenbilushko commented on b2c.implementation/UI/StoreUI.cs
> +
remove line

2021-06-01 20:13 UTC, yevhenbilushko commented on b2c.implementation/UI/StoreUI.cs
> +                if(newProduct == "0")
please add brackets for "if"
add add space after "If" "if (newProduct == "0")"

2021-06-01 20:13 UTC, yevhenbilushko commented on b2c.implementation/UI/StoreUI.cs
> +
remove line

2021-06-01 20:13 UTC, yevhenbilushko commented on b2c.implementation/abstracts/IStoreService.cs
> +
remove line

2021-06-01 20:46 UTC, serhii-shkodenko commented on b2c.implementation/Services/CustomerService.cs
> +            catch (System.InvalidOperationException)
> На самом деле, если словарь заказов пуст будет исключение типа System.InvalidOperationException. Поэтому я и присваиваю в блоке catch id=1. А если не пуст - я нахожу максимальный Id и прибавляю к нему единицу.

Достаточно сделать как-то так:
        
```
        var dictionary = new Dictionary<int, string> 
        {
            { 1, "Simple" }
        };

        if (dictionary.Keys.Count > 0)
        {
            var maxId = dictionary.Keys.Max() + 1;
        }
```

2021-06-01 20:48 UTC, serhii-shkodenko commented on b2c.implementation/Services/CustomerService.cs
> +            catch (System.InvalidOperationException)
> > На самом деле, если словарь заказов пуст будет исключение типа System.InvalidOperationException. Поэтому я и присваиваю в блоке catch id=1. А если не пуст - я нахожу максимальный Id и прибавляю к нему единицу.
> 
> Достаточно сделать как-то так:
> 
> ```
>         if (dictionary.Keys.Count > 0)
>         {
>             var maxId = dictionary.Keys.Max() + 1;
>         }
> ```

Или даже так:
```
id = dictionary.Keys.Count > 0
    ? dictionary.Keys.Max() + 1
    : 1;
```

2021-06-06 14:02 UTC, serhii-shkodenko approved these changes
Выглядит хорошо. Можно мержить.

2021-06-07 08:09 UTC, merged